// Dining Menu Data Structure
// This file contains the structured menu data for Dehaati Restaurant

const diningMenu = [
    {
        categoryTitle: "Appetizers",
        hideCategory: false,
        menuItems: [
            {
                title: "Vada Pav",
                description: "Mumbai-style vada pav with chutneys",
                cost: 5.99,
                spiceLevel: "mild",
                region: "Mumbai",
                imageLink: "images-for-menu/Appetizers_Vada_Pav.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Kothimbir Vadi",
                description: "Snacks made with coriander and besan",
                cost: 6.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Appetizers_Kothimbir_Vadi.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Prawns Rava Fry",
                description: "Coastal Maharashtrian semolina-crusted prawns",
                cost: 14.00,
                spiceLevel: "medium",
                region: "Coastal Maharashtra",
                imageLink: "images-for-menu/Appetizers_Prawns_Rava_Fry.webp",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            }
        ]
    },
    {
        categoryTitle: "Thali",
        hideCategory: false,
        menuItems: [
            {
                title: "Pune Chicken Thali",
                description: "Village style, Spicy, Rustic Chicken Sukkha, Rassa, yellow curry/Alani, solkadi, rice, chapati/Jowar bhakari, Gulab Jamun",
                cost: 24.99,
                spiceLevel: "spicy",
                region: "Pune",
                imageLink: "images-for-menu/Thali_Pune_Chicken.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Kolhapuri Chicken Thali",
                description: "Chicken Masala, Tambda, pandra solkadi, rice, chapati/Jowar bhakari, Gulab Jamun",
                cost: 25.99,
                spiceLevel: "spicy",
                region: "Kolhapur",
                imageLink: "images-for-menu/Thali_Kolhapur_Chicken.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Kolhapuri Mutton Thali",
                description: "Mutton Masala, Tambda, pandra solkadi, rice, chapati/Jowar bhakari, Gulab Jamun. Make it special: Mutton Lonche/Pickle + Pulav +$5",
                cost: 28.99,
                spiceLevel: "spicy",
                region: "Kolhapur",
                imageLink: "images-for-menu/Thali_Mutton_Masala.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Egg Thali",
                description: "Egg Malasa, Egg Rassa, Chapati/Bhakri, Solkadi, Rice, Gulab Jamun",
                cost: 23.99,
                spiceLevel: "medium",
                region: "Maharashtra",
                imageLink: "images-for-menu/Thali_Egg.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Veg Thali",
                description: "Veg Gravy, Dry Vegi, Chapati/Jowar Bhakari, Solkadi, Sweet, Fried Item, Papad/Kurdai, Daal, Rice",
                cost: 19.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Thali_Veg.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Kids Chicken Thali",
                description: "Chapati, Alani rassa, Chicken Masala, SolKadi, Rice, Gulab Jamun",
                cost: 11.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Kids Veg Thali",
                description: "Paneer, Chapati, SolKadi, Rice, Gulab Jamun",
                cost: 9.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            }
        ]
    },
    {
        categoryTitle: "Plates",
        hideCategory: false,
        menuItems: [
            {
                title: "Puneri Chicken Sukkha",
                description: "Village style spicy dry chicken preparation",
                cost: 15.99,
                spiceLevel: "spicy",
                region: "Pune",
                imageLink: "images-for-menu/Plates_Puneri_Chicken_Sukha.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Kolhapuri Chicken Masala",
                description: "Spicy Kolhapuri style chicken curry",
                cost: 15.99,
                spiceLevel: "spicy",
                region: "Kolhapur",
                imageLink: "images-for-menu/Plates_Kolhapuri_Chicken_Masala.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Kolhapuri Mutton Masala",
                description: "Spicy Kolhapuri style mutton curry",
                cost: 17.99,
                spiceLevel: "spicy",
                region: "Kolhapur",
                imageLink: "images-for-menu/Plates_Kolhapuri_Mutton_Masala.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Egg Curry",
                description: "Spicy egg curry",
                cost: 17.99,
                spiceLevel: "spicy",
                region: "Maharashtra",
                imageLink: "images-for-menu/Plates_Egg_Curry.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Egg Masala",
                description: "Spicy egg masala",
                cost: 15.99,
                spiceLevel: "spicy",
                region: "Maharashtra",
                imageLink: "images-for-menu/Plates_Egg_Masala.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            }
        ]
    },
    {
        categoryTitle: "Sides",
        hideCategory: false,
        menuItems: [
            {
                title: "Pune Chicken Rassa",
                description: "Thin spicy chicken curry",
                cost: 5.99,
                spiceLevel: "spicy",
                region: "Pune",
                imageLink: "images-for-menu/Sides_Puneri_Chicken_Rassa.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Alani/Yellow Rassa",
                description: "Yellow curry with turmeric and spices",
                cost: 5.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Sides_Alani_Rassa.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Kolhapuri Chicken Tamda Rassa",
                description: "Red spicy mutton curry from Kolhapur",
                cost: 5.99,
                spiceLevel: "spicy",
                region: "Kolhapur",
                imageLink: "images-for-menu/Sides_Chicken_Tamda_Rassa.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },            
            {
                title: "Kolhapuri Pandra Rassa",
                description: "White curry from Kolhapur",
                cost: 6.99,
                spiceLevel: "mild",
                region: "Kolhapur",
                imageLink: "images-for-menu/Sides_Pandra_Rassa.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            }
        ]
    },
    {
        categoryTitle: "Rice",
        hideCategory: false,
        menuItems: [
            {
                title: "Chicken Pulav",
                description: "Fragrant basmati rice cooked with chicken and aromatic spices",
                cost: 14.99,
                spiceLevel: "medium",
                region: "Maharashtra",
                imageLink: "images-for-menu/Rice_Chicken_Pulav.avif",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Plain Rice",
                description: "Steamed basmati rice",
                cost: 2.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Rice_Plain_Rice.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            },
            {
                title: "Alani Rice",
                description: "Yellow rice with turmeric and spices",
                cost: 9.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Rice_Alani_Rice.webp",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            }
        ]
    },
    {
        categoryTitle: "Breads",
        hideCategory: false,
        menuItems: [
            {
                title: "Chapati",
                description: "Soft whole wheat flatbread",
                cost: 2.50,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Breads_Chapati.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            },
            {
                title: "Jowar Bhakari",
                description: "Traditional gluten-free sorghum flatbread, freshly made",
                cost: 3.50,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Breads_Jowar_Bhakari.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            }
        ]
    },
    {
        categoryTitle: "Sweets",
        hideCategory: false,
        menuItems: [
            {
                title: "Ice Cream",
                description: "Creamy ice cream",
                cost: 4.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: false,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Gulab Jamun",
                description: "Sweet milk dumplings in sugar syrup",
                cost: 4.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Sweets_Gulab_Jamun.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Kesar Pista Rabdi",
                description: "Sweet milk rabdi with kesar and pista",
                cost: 5.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Sweets_Kesar_Pista_Rabdi.webp",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Shrikhand",
                description: "Sweet yogurt with sugar and spices",
                cost: 5.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Sweets_Shrikhand.webp",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            }
        ]
    },
    {
        categoryTitle: "Beverages",
        hideCategory: false,
        menuItems: [
            {
                title: "Special Sarbat",
                description: "Traditional sweet drink",
                cost: 4.00,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Beverages_Sarbat.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            },
            {
                title: "Tea",
                description: "Hot tea",
                cost: 3.00,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Beverages_Tea.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            },
            {
                title: "Coffee",
                description: "Hot coffee",
                cost: 5.00,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Beverages_Coffee.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            },
            {
                title: "Solkadi",
                description: "Kokum-coconut digestive drink",
                cost: 5.00,
                spiceLevel: "mild",
                region: "Kolhapur",
                imageLink: "images-for-menu/Beverages_Solkadi.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Mango Lassi",
                description: "Sweet mango yogurt drink",
                cost: 5.00,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Beverages_Mango_Lassi.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Coke, Sprite, Diet Coke",
                description: "Soft drinks",
                cost: 2.00,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "images-for-menu/Beverages_Coke.jpeg",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            }
        ]
    }
];
